version: "3.8"
services:
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - viewtist

  chatting-api:
    build:
      context: ./chatting-api
      dockerfile: Dockerfile
    depends_on:
      - core
    ports:
      - "8081:8081"
    networks:
      - viewtist

  streaming-api:
    build:
      context: ./streaming-api
      dockerfile: Dockerfile
    depends_on:
      - core
    ports:
      - "8082:8082"
    networks:
      - viewtist

networks:
  viewtist: