version: "3.8"
services:
  common:
    build:
      context: ./common
      dockerfile: Dockerfile
    image: limhyeantaek/common
    ports:
      - "8083:8083"
    networks:
      - viewtist
    platform: linux/amd64

  chatting-api:
    build:
      context: ./chatting-api
      dockerfile: Dockerfile
    image: limhyeantaek/chatting-api
    ports:
      - "443:443"
    networks:
      - viewtist
    platform: linux/amd64

  streaming-api:
    build:
      context: ./streaming-api
      dockerfile: Dockerfile
    image: limhyeantaek/streaming-api
    ports:
      - "8082:8082"
    networks:
      - viewtist
    platform: linux/amd64

networks:
  viewtist:
