version: "3.8"
services:
  common:
    build:
      context: ./common
      dockerfile: Dockerfile
    image: limhyeantaek/common
    ports:
      - "8080:8080"
    networks:
      - viewtist
    platform: linux/amd64

  chatting-api:
    build:
      context: ./chatting-api
      dockerfile: Dockerfile
    image: limhyeantaek/chatting-api
    ports:
      - "8081:8081"
    networks:
      - viewtist
    platform: linux/arm64

  streaming-api:
    build:
      context: ./streaming-api
      dockerfile: Dockerfile
    image: limhyeantaek/streaming-api
    ports:
      - "8082:8082"
    networks:
      - viewtist
    platform: linux/amd64

networks:
  viewtist:
