spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${secrets.ENDPOINT}:3306/${secrets.DATABASE_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${secrets.DATABASE_USER_NAME}
    password: ${secrets.DATABASE_USER_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  # multipartFile 용량 늘려주는 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      accessKey: ${secrets.S3_ACCESS_KEY}
      secretKey: ${secrets.S3_SECRET_KEY}
    s3: #버킷이름
      bucket: viewtistbucket
    region: #S3 지역
      static: ap-northeast-2
    stack:
      auto: false